version: '3.8'

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: travel-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - travel-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travel-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    ports:
      - 8000:8000
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=travel_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
    networks:
      - travel-network

  mysql:
    image: mysql:8.0
    container_name: travel-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=travel_db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - travel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: travel-phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - 8080:80
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local